#pragma once

#include "Core/CoreMinimal.h"
#include "RHI/ERHIDescriptorType.h"
#include "RHI/ERHIFormat.h"
#include "RHI/ERHIIndexType.h"
#include "RHI/ERHIPipelineState.h"
#include "RHI/ERHIQueueType.h"
#include "RHI/ERHIResourceUsage.h"
#include "RHI/ERHIResult.h"
#include "RHI/ERHIRuntimeMode.h"
#include "RHI/FRHIRuntimeSnapshot.h"
#include "RHI/FRHIPresentationSurfaceDesc.h"
#include "RHI/FRHISwapchainDesc.h"
#include "RHI/IRHIPresentationSurface.h"
#include "RHI/ERHISamplerMode.h"
#include "RHI/ERHIShaderStage.h"
#include "RHI/ERHITextureDimension.h"
#include "RHI/FRHIBufferDesc.h"
#include "RHI/FRHIComputePipelineDesc.h"
#include "RHI/FRHIDescriptorBinding.h"
#include "RHI/FRHIDeviceCapabilities.h"
#include "RHI/FRHIFramebufferDesc.h"
#include "RHI/FRHIGraphicsPipelineDesc.h"
#include "RHI/FRHIPipelineLayoutDesc.h"
#include "RHI/FRHIRenderPassDesc.h"
#include "RHI/FRHISamplerDesc.h"
#include "RHI/FRHIShaderModuleDesc.h"
#include "RHI/FRHITextureDesc.h"
#include "RHI/FRHITextureUploadDesc.h"
#include "RHI/FRHITextureBufferCopyRegion.h"
#include "RHI/IRHIBuffer.h"
#include "RHI/IRHICommandBuffer.h"
#include "RHI/IRHICommandQueue.h"
#include "RHI/IRHIComputePipeline.h"
#include "RHI/IRHIDescriptorSet.h"
#include "RHI/IRHIDevice.h"
#include "RHI/IRHIFence.h"
#include "RHI/IRHIFramebuffer.h"
#include "RHI/IRHIGraphicsPipeline.h"
#include "RHI/IRHIPipelineLayout.h"
#include "RHI/IRHIRenderPass.h"
#include "RHI/IRHISampler.h"
#include "RHI/IRHISemaphore.h"
#include "RHI/IRHIShaderModule.h"
#include "RHI/IRHISwapchain.h"
#include "RHI/IRHITexture.h"

// RHI layer minimal header — abstract hardware interface
namespace Stoner::RHI
{
} // namespace Stoner::RHI
