#pragma once

#include "Asset/EAssetResult.h"
#include "Asset/FAssetDiagnostics.h"
#include "Asset/FAssetDigest.h"
#include "Asset/FAssetDispatch.h"
#include "Asset/FAssetExtensionRegistry.h"
#include "Asset/FAssetId.h"
#include "Asset/FAssetInspection.h"
#include "Asset/FAssetImportRequest.h"
#include "Asset/FImageAsset.h"
#include "Asset/FImageImport.h"
#include "Asset/FImageInspection.h"
#include "Asset/FImageMip.h"
#include "Asset/FImageTypes.h"
#include "Asset/FKTX2TextureArtifact.h"
#include "Asset/FKTX2TextureCodec.h"
#include "Asset/FKTX2TextureLoader.h"
#include "Asset/FTextureCook.h"
#include "Asset/FTextureTranscode.h"
#include "Asset/FTextureAsset.h"
#include "Asset/FAssetDependency.h"
#include "Asset/FAssetMetadata.h"
#include "Asset/FAssetParticipant.h"
#include "Asset/FAssetPayload.h"
#include "Asset/FAssetRegistry.h"
#include "Asset/FAssetSource.h"
#include "Asset/FAssetVersion.h"
#include "Asset/FAssetSourceVersionRecord.h"
#include "Asset/FMaterialAsset.h"
#include "Asset/FMaterialInstanceAsset.h"
#include "Asset/FMaterialShaderAssetLimits.h"
#include "Asset/FMaterialShaderInspection.h"
#include "Asset/FMaterialShaderSourceLoader.h"
#include "Asset/FMaterialShaderTypes.h"
#include "Asset/FShaderAsset.h"
#include "Asset/FShaderPayloadAsset.h"
#include "Asset/FShaderSourceAsset.h"
#include "Asset/TSoftAssetRef.h"
#include "Asset/IAssetCooker.h"
#include "Asset/IAssetImporter.h"
#include "Asset/IAssetLoader.h"
#include "Asset/IAssetResolver.h"

namespace Stoner::Asset
{
} // namespace Stoner::Asset
